---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-equipment-pvc
  namespace: itify
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-equipment
  namespace: itify
spec:
  selector:
    matchLabels:
      app: postgres-equipment
  serviceName: postgres-equipment
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-equipment
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: itify_equipment
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: itify-postgres-secret
                  key: equipment-password
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-equipment-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-equipment
  namespace: itify
spec:
  selector:
    app: postgres-equipment
  ports:
    - port: 5432
      targetPort: 5432