version: "3.8"

services:
  itify-db:
    image: postgres:13.2-alpine
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: itify-app
      POSTGRES_DB: itify-app
      POSTGRES_PASSWORD: itify-app
    volumes:
      - itify-db-vol:/var/lib/postgresql/data

volumes:
  itify-db-vol: